name: Build and test

on:
    push:
        branches: [main]

jobs:
    test:
        name: "Build and test Release config"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4
              with:
                  submodules: "true"

              timeout-minutes: 2

            - name: "Configure CMake"
              run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release

            - name: "Build project"
              run: cmake --build build --target all --config Release

            - name: "Run tests"
              run: ctest --test-dir build
